name: 'Restorecommerce System Setup'
description: 'Launch the Restorecommerce docker compose system'

inputs:
  backing-only:
    description: 'Whether to setup all or only backing services'
    required: false
    default: 'true'
  restart:
    description: 'Whether to restart right after setup'
    required: false
    default: 'false'
  import:
    description: 'Whether to import data after setup'
    required: false
    default: 'false'
  shutdown:
    description: 'Services to shutdown after setup'
    required: false
    default: ''

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/index.js'
